package cmd

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/Jonas-Marty/ad-cli/pkg/ui"
	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Set up shell integration and check prerequisites",
	Long: `Checks prerequisites (Azure CLI + azure-devops extension) and configures
shell integration for both Git Bash and PowerShell:

  • Adds dvo.exe to PATH
  • Installs bash completion
  • Installs PowerShell completion

Safe to re-run — uses markers so no duplicate entries are added.`,
	RunE: runInit,
}

func init() {
	rootCmd.AddCommand(initCmd)
}

// ── entry point ────────────────────────────────────────────────────────────

func runInit(_ *cobra.Command, _ []string) error {
	printBanner("dvo — Azure DevOps CLI  •  Setup")
	fmt.Println()

	checkPrerequisites()
	fmt.Println()

	setupShellIntegration()

	ui.Success.Println("You're all set! Try: dvo --help")
	return nil
}

// ── prerequisites ──────────────────────────────────────────────────────────

func checkPrerequisites() {
	ui.Info.Println("Checking prerequisites...")
	fmt.Println()

	// 1. az CLI
	if _, err := exec.LookPath("az"); err != nil {
		ui.Error.Println("  ✗ Azure CLI (az) not found")
		ui.Warning.Println("    Install: https://aka.ms/installazurecliwindows")
		ui.Warning.Println("    Or: winget install Microsoft.AzureCLI")
	} else {
		ver, _ := exec.Command("az", "version", "--query", `"azure-cli"`, "-o", "tsv").Output()
		ui.Success.Printf("  ✓ Azure CLI found (%s)\n", strings.TrimSpace(string(ver)))

		// 1b. azure-devops extension
		out, err := exec.Command("az", "extension", "list", "--query", "[?name=='azure-devops'].name", "-o", "tsv").Output()
		if err != nil || strings.TrimSpace(string(out)) == "" {
			ui.Warning.Println("  ⚠  azure-devops extension not installed")
			if promptYesNo("    Install it now?", true) {
				if err := ui.RunStreaming("Installing azure-devops extension",
					exec.Command("az", "extension", "add", "--name", "azure-devops")); err != nil {
					ui.Error.Printf("    Failed: %v\n", err)
					ui.Warning.Println("    Run manually: az extension add --name azure-devops")
				} else {
					ui.Success.Println("  ✓ azure-devops extension installed")
				}
			}
		} else {
			ui.Success.Println("  ✓ azure-devops extension installed")
		}
	}

	// 2. git
	if _, err := exec.LookPath("git"); err != nil {
		ui.Error.Println("  ✗ git not found — all commands require git")
	} else {
		ver, _ := exec.Command("git", "version").Output()
		ui.Success.Printf("  ✓ git found (%s)\n", strings.TrimSpace(string(ver)))
	}
}

// ── shell integration ──────────────────────────────────────────────────────

func setupShellIntegration() {
	exe, err := os.Executable()
	if err != nil {
		ui.Warning.Printf("Could not determine binary location: %v\n", err)
		return
	}
	binDir := filepath.Dir(exe)

	printSection("Shell Integration")
	fmt.Println()

	setupBashIntegration(binDir)
	fmt.Println()
	setupPowerShellIntegration(binDir)
	fmt.Println()
}

const bashBeginMarker = "###-begin-dvo-completions-###"
const bashEndMarker = "###-end-dvo-completions-###"

func setupBashIntegration(binDir string) {
	home, err := os.UserHomeDir()
	if err != nil {
		ui.Warning.Println("Could not find home directory, skipping Bash setup.")
		return
	}
	bashrc := filepath.Join(home, ".bashrc")
	unixBinDir := toUnixPath(binDir)
	unixCompletionFile := toUnixPath(BashCompletionPath(binDir))
	unixExe := toUnixPath(filepath.Join(binDir, "dvo.exe"))

	// Write the version-stamped completion scripts. Going through the same
	// writer as 'dvo completion regen' keeps the "# dvo-version:" header in
	// place, so the auto-refresh check below does not fire on the first shell.
	if _, err := writeStampedCompletions(binDir); err != nil {
		ui.Warning.Printf("Could not write completion scripts: %v\n", err)
	}

	configBlock := fmt.Sprintf(
		"%s\n"+
			"#\n"+
			"# dvo — Azure DevOps CLI: PATH and completion\n"+
			"# Generated by: dvo init\n"+
			"#\n"+
			"export PATH=\"%s:$PATH\"\n\n"+
			"# Wrapper so 'dvo<Tab>' completes to 'dvo' (not 'dvo.exe')\n"+
			"dvo() { dvo.exe \"$@\"; }\n\n"+
			"# Auto-refresh completions when the binary version changes. Compares the\n"+
			"# version stamp in the completion file against the running binary and only\n"+
			"# regenerates when they differ, so an unchanged build costs nothing.\n"+
			"_dvo_maybe_regen_completion() {\n"+
			"    local exe=\"%s\"\n"+
			"    local completion_file=\"%s\"\n"+
			"    [ -x \"$exe\" ] || return\n"+
			"    local current_ver stored_ver\n"+
			"    current_ver=\"$(\"$exe\" version --short 2>/dev/null)\" || return\n"+
			"    stored_ver=\"$(grep -m1 '^# dvo-version:' \"$completion_file\" 2>/dev/null | awk '{print $3}')\"\n"+
			"    [ \"$current_ver\" = \"$stored_ver\" ] && return\n"+
			"    \"$exe\" completion regen >/dev/null 2>&1 \\\n"+
			"        && printf 'dvo: completions regenerated (%%s)\\n' \"$current_ver\" >&2\n"+
			"}\n"+
			"_dvo_maybe_regen_completion\n\n"+
			"# Bash completion\n"+
			"[ -f \"%s\" ] && source \"%s\"\n"+
			"%s\n",
		bashBeginMarker, unixBinDir, unixExe, unixCompletionFile,
		unixCompletionFile, unixCompletionFile, bashEndMarker)

	writeMarkerBlock(bashrc, bashBeginMarker, bashEndMarker, configBlock, "Git Bash", "~/.bashrc", "source ~/.bashrc")
}

func setupPowerShellIntegration(binDir string) {
	psProfile := powershellProfile()
	if psProfile == "" {
		ui.Warning.Println("Could not determine PowerShell profile path, skipping PowerShell setup.")
		return
	}

	// The completion scripts are written by setupBashIntegration, which runs
	// first and emits both files.
	completionFile := PowerShellCompletionPath(binDir)
	exe := filepath.Join(binDir, "dvo.exe")

	const psBegin = "###-begin-dvo-completions-###"
	const psEnd = "###-end-dvo-completions-###"

	configBlock := fmt.Sprintf(
		"\n%s\n"+
			"#\n"+
			"# dvo — Azure DevOps CLI: PATH and completion\n"+
			"# Generated by: dvo init\n"+
			"#\n"+
			"$env:PATH = \"%s\" + [IO.Path]::PathSeparator + $env:PATH\n\n"+
			"# Auto-refresh completions when the binary version changes. Compares the\n"+
			"# version stamp in the completion file against the running binary and only\n"+
			"# regenerates when they differ, so an unchanged build costs nothing.\n"+
			"$dvoExe = \"%s\"\n"+
			"$dvoCompletion = \"%s\"\n"+
			"if (Test-Path $dvoExe) {\n"+
			"    $dvoCurrent = & $dvoExe version --short 2>$null\n"+
			"    $dvoStored = $null\n"+
			"    if (Test-Path $dvoCompletion) {\n"+
			"        $dvoStored = (Select-String -Path $dvoCompletion -Pattern '^# dvo-version: (.+)$' |\n"+
			"            Select-Object -First 1).Matches.Groups[1].Value\n"+
			"    }\n"+
			"    if ($dvoCurrent -and $dvoCurrent -ne $dvoStored) {\n"+
			"        & $dvoExe completion regen *> $null\n"+
			"        Write-Host \"dvo: completions regenerated ($dvoCurrent)\"\n"+
			"    }\n"+
			"}\n\n"+
			"# PowerShell completion\n"+
			"if (Test-Path \"%s\") { . \"%s\" }\n"+
			"%s\n",
		psBegin, binDir, exe, completionFile, completionFile, completionFile, psEnd)

	_ = os.MkdirAll(filepath.Dir(psProfile), 0755)
	writeMarkerBlock(psProfile, psBegin, psEnd, configBlock, "PowerShell", psProfile, ". $PROFILE")
}

// writeMarkerBlock idempotently inserts or replaces a marker-fenced block in a file.
func writeMarkerBlock(filePath, begin, end, block, shell, displayPath, reloadCmd string) {
	content, _ := os.ReadFile(filePath)
	existing := string(content)

	if strings.Contains(existing, begin) && strings.Contains(existing, end) {
		startIdx := strings.Index(existing, begin)
		endIdx := strings.Index(existing, end) + len(end)
		newContent := existing[:startIdx] + block + existing[endIdx:]
		if err := os.WriteFile(filePath, []byte(newContent), 0644); err != nil {
			ui.Warning.Printf("  Could not update %s: %v\n", filePath, err)
			return
		}
		ui.Success.Printf("  ✓ %s: updated %s\n", shell, displayPath)
	} else {
		f, err := os.OpenFile(filePath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
		if err != nil {
			ui.Warning.Printf("  Could not write to %s: %v\n", filePath, err)
			return
		}
		defer f.Close()
		if !strings.HasSuffix(existing, "\n") && existing != "" {
			_, _ = f.WriteString("\n")
		}
		_, _ = f.WriteString("\n" + block + "\n")
		ui.Success.Printf("  ✓ %s: configured PATH and completion in %s\n", shell, displayPath)
	}
	ui.Info.Printf("    Reload with:  %s\n", reloadCmd)
}

// ── helpers ────────────────────────────────────────────────────────────────

func powershellProfile() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	if runtime.GOOS == "windows" {
		return filepath.Join(home, "Documents", "PowerShell", "Microsoft.PowerShell_profile.ps1")
	}
	return filepath.Join(home, ".config", "powershell", "Microsoft.PowerShell_profile.ps1")
}

func toUnixPath(p string) string {
	if runtime.GOOS != "windows" {
		return p
	}
	p = filepath.ToSlash(p)
	if len(p) >= 2 && p[1] == ':' {
		drive := strings.ToLower(string(p[0]))
		return "/" + drive + p[2:]
	}
	return p
}

func promptYesNo(question string, defaultYes bool) bool {
	suffix := " [Y/n]: "
	if !defaultYes {
		suffix = " [y/N]: "
	}
	fmt.Print(question + suffix)
	reader := bufio.NewReader(os.Stdin)
	input, err := reader.ReadString('\n')
	if err != nil {
		fmt.Println()
		return false
	}
	input = strings.TrimSpace(strings.ToLower(input))
	if input == "" {
		return defaultYes
	}
	return input == "y" || input == "yes"
}

func printBanner(text string) {
	line := strings.Repeat("─", len(text)+4)
	fmt.Println(line)
	fmt.Println("  " + text)
	fmt.Println(line)
}

func printSection(text string) {
	fmt.Println(text)
	fmt.Println(strings.Repeat("─", len(text)))
}
